plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - get-token-step.md

theme: jekyll-theme-hacker

title: Folder Downloader 2
description: This is the secondary folder downloader site for TS4T, powered by GitZip, in case the first one does not work. It downloads and zips folders.

github:
  is_project_page: false
